[serve]
port = 8089

[build]
ignore = [
    "node_modules/**",
    "dist/**",
    ".git/**",
    "logs/**",
    "tmp/**",
    "*.log",
    "*.tmp",
    "*.bak",
    "*.swp",
    "*.swo",
    "*.DS_Store",
    "Thumbs.db",
    "coverage/**",
    "*.test.js",
    "*.spec.js",
    "*.test.ts",
    "*.spec.ts"
]